	.TITLE	Minuet in G Major

;++
;      Copyright (C) 2021-2024 By Spare Time Gizmos, Milpitas CA.
;
;   This program is free software; you can redistribute it and/or modify
; it under the terms of the GNU General Public License as published by
; the Free Software Foundation; either version 2 of the License, or
; (at your option) any later version.
;
;   This program is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
; for more details.
;
;   You should have received a copy of the GNU General Public License along
; with this program; if not, write to the Free Software Foundation, Inc.,
; 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
;--
;0000000001111111111222222222233333333334444444444555555555566666666667777777777
;1234567890123456789012345678901234567890123456789012345678901234567890123456789

;++
;   This is the music demo used by the SBC1802 "TEST PSG" and is the "Minuet in
; G Major", often attributed to J.S. Bach but more likely written by Christian
; Petzold, c.a. 1725.  Big band leader Freddy Martin often played this piece
; during the late 1940s, and later songwriters Linzer and Randell wrote lyrics
; for it.  That version, "A Lover's Concerto," was recorded by girl group "The
; Toys" and made it to #2 on the Billboard Hot 100 in 1965.  Other than a 
; change in the time signature, "A Lover's Concerto" is exactly the same melody.
; There are many, many examples of pop/rock songs that were inspired by
; classical music, but to my knowledge this is the one that is an exact copy
; of the original piece.
;
;   This data was generated from a MIDI file using by Len Shustek's MIDITONES
; program -
;
;	http://code.google.com/p/miditones/
;
; Len's program takes a MIDI file, renders it for six basic tone generators,
; and then outputs a simple stream of byte codes for the music.  Len documents
; the byte codes fairly well on his web page, so I won't repeat that part here.
;
;   This particular byte stream was generated using the command line -
;
;	MIDItones -t=6 -k=12 -a -pi "Minuet in G"
;
;   The rommerge program merges the .hex file generated by assembling this file
; into the SBC1802 EPROM image.  You're free to substitute a new song, but the
; space in the EPROM is limited - there are only 1248 bytes, from $EB00 to 
; $EFDF, available.
;--
	.MSFIRST \ .PAGE \ .CODES
	.NOLIST
	.INCLUDE "sbc1802.inc"	; SBC1802 hardware and environment definitions
	.LIST

	.ORG	MUSIC
	.BYTE	$90, $56, $91, $4A, $92, $47, $93, $43, $01, $90, $90, $4F
	.BYTE	$00, $C8, $90, $51, $00, $C1, $94, $45, $00, $06, $90, $53
	.BYTE	$81, $82, $83, $00, $C5, $91, $54, $00, $03, $80, $00, $C2
	.BYTE	$90, $47, $84, $00, $03, $91, $56, $01, $90, $81, $00, $07
	.BYTE	$91, $4F, $00, $C8, $81, $00, $C1, $91, $4F, $01, $8D, $90
	.BYTE	$48, $00, $03, $91, $58, $01, $90, $81, $00, $03, $91, $54
	.BYTE	$00, $C5, $92, $56, $00, $03, $81, $00, $C5, $91, $58, $82
	.BYTE	$00, $C8, $91, $5A, $00, $BE, $92, $47, $00, $07, $80, $00
	.BYTE	$03, $81, $00, $03, $90, $5B, $01, $90, $90, $4F, $00, $C8
	.BYTE	$80, $00, $C5, $90, $4F, $01, $86, $82, $00, $07, $91, $45
	.BYTE	$00, $03, $80, $00, $03, $90, $54, $01, $90, $90, $56, $00
	.BYTE	$C8, $90, $54, $00, $C5, $92, $53, $00, $03, $80, $00, $C5
	.BYTE	$90, $51, $82, $00, $C5, $81, $00, $03, $90, $43, $00, $07
	.BYTE	$91, $53, $01, $8C, $92, $54, $00, $04, $81, $00, $C4, $91
	.BYTE	$53, $82, $00, $C8, $91, $51, $00, $C8, $91, $4F, $00, $C5
	.BYTE	$80, $00, $03, $90, $4E, $91, $4A, $00, $64, $81, $01, $29
	.BYTE	$91, $4F, $92, $47, $00, $03, $80, $00, $61, $82, $00, $64
	.BYTE	$90, $51, $81, $00, $C8, $90, $43, $00, $03, $91, $53, $00
	.BYTE	$61, $80, $00, $67, $90, $4F, $81, $00, $C2, $91, $4A, $00
	.BYTE	$06, $80, $00, $07, $90, $53, $00, $35, $92, $54, $00, $18
	.BYTE	$80, $00, $2B, $82, $00, $0A, $90, $53, $00, $39, $92, $54
	.BYTE	$00, $0A, $80, $00, $38, $82, $00, $25, $90, $53, $00, $43
	.BYTE	$80, $00, $1E, $81, $00, $03, $90, $3E, $00, $03, $91, $51
	.BYTE	$00, $C5, $80, $00, $03, $90, $48, $00, $C5, $92, $47, $00
	.BYTE	$03, $80, $00, $C5, $90, $45, $82, $00, $C8, $80, $00, $03
	.BYTE	$90, $56, $91, $47, $01, $90, $80, $00, $04, $90, $4F, $00
	.BYTE	$C1, $92, $51, $00, $07, $80, $00, $BE, $90, $45, $00, $03
	.BYTE	$82, $00, $03, $81, $00, $04, $91, $53, $00, $C8, $91, $54
	.BYTE	$00, $BE, $90, $43, $00, $0A, $91, $56, $01, $86, $80, $00
	.BYTE	$03, $90, $47, $00, $07, $91, $4F, $00, $C1, $80, $00, $07
	.BYTE	$81, $00, $BE, $90, $43, $00, $06, $91, $4F, $01, $8A, $90
	.BYTe	$48, $00, $03, $92, $58, $00, $03, $81, $01, $8A, $91, $54
	.BYTE	$00, $03, $82, $00, $C5, $91, $56, $00, $C8, $91, $58, $00
	.BYTE	$C4, $92, $5A, $00, $04, $81, $00, $C4, $82, $00, $04, $80
	.BYTE	$00, $03, $90, $5B, $91, $47, $01, $8D, $92, $4F, $00, $03
	.BYTE	$80, $81, $00, $03, $90, $48, $00, $C2, $91, $47, $82, $00
	.BYTE	$06, $80, $00, $C2, $90, $4F, $91, $45, $00, $C8, $91, $43
	.BYTE	$00, $C8, $90, $54, $81, $00, $03, $91, $45, $01, $8D, $80
	.BYTE	$00, $06, $90, $56, $00, $C8, $90, $54, $00, $C5, $91, $42
	.BYTE	$00, $03, $90, $53, $00, $BE, $92, $51, $00, $0A, $80, $00
	.BYTE	$BE, $82, $00, $04, $90, $53, $00, $03, $91, $43, $01, $86
	.BYTE	$92, $54, $00, $07, $80, $00, $C1, $90, $53, $82, $00, $C8
	.BYTE	$80, $00, $03, $90, $51, $00, $04, $92, $47, $00, $03, $81
	.BYTE	$00, $C1, $90, $4F, $00, $C8, $80, $00, $04, $90, $48, $82
	.BYTE	$00, $03, $91, $51, $01, $94, $92, $4A, $00, $03, $93, $53
	.BYTE	$80, $00, $04, $81, $00, $D3, $90, $51, $00, $6A, $83, $00
	.BYTE	$6F, $82, $00, $04, $91, $3E, $00, $03, $92, $4F, $00, $0F
	.BYTE	$80, $00, $C9, $82, $00, $10, $90, $4E, $00, $E3, $81, $00
	.BYTE	$04, $91, $43, $00, $08, $92, $4F, $00, $04, $80, $03, $B0
	.BYTE	$81, $00, $04, $90, $37, $00, $04, $82, $01, $86, $91, $5F
	.BYTE	$00, $06, $90, $43, $01, $8A, $81, $00, $03, $91, $5B, $00
	.BYTE	$C5, $92, $5D, $00, $03, $81, $00, $C1, $91, $5F, $00, $04
	.BYTE	$82, $00, $C4, $91, $5B, $00, $C8, $81, $00, $07, $91, $42
	.BYTE	$00, $03, $92, $5D, $80, $01, $8A, $90, $56, $00, $06, $82
	.BYTE	$00, $BB, $92, $58, $00, $07, $80, $00, $C1, $90, $5A, $82
	.BYTE	$00, $0A, $81, $00, $BE, $80, $00, $03, $90, $56, $00, $C8
	.BYTE	$80, $00, $04, $90, $5B, $91, $40, $01, $90, $90, $43, $81
	.BYTE	$00, $06, $91, $58, $00, $C2, $80, $00, $06, $90, $5A, $81
	.BYTE	$00, $C2, $91, $40, $00, $06, $90, $5B, $00, $C2, $92, $56
	.BYTE	$00, $06, $80, $00, $C2, $90, $55, $91, $45, $82, $01, $90
	.BYTE	$80, $00, $03, $90, $53, $00, $C8, $80, $00, $03, $90, $55
	.BYTE	$00, $C2, $81, $00, $06, $90, $51, $91, $39, $01, $2C, $80
	.BYTE	$00, $5E, $90, $45, $00, $06, $81, $00, $04, $91, $51, $00
	.BYTE	$C4, $92, $53, $00, $04, $81, $00, $C1, $91, $55, $00, $03
	.BYTE	$82, $00, $C5, $91, $56, $00, $C8, $81, $00, $03, $91, $58
	.BYTE	$00, $C8, $91, $5A, $00, $C2, $80, $00, $03, $90, $47, $00
	.BYTE	$03, $91, $5B, $00, $61, $80, $00, $03, $81, $01, $26, $90
	.BYTE	$4A, $00, $06, $91, $5A, $00, $5E, $80, $00, $06, $81, $01
	.BYTE	$2C, $90, $49, $00, $04, $91, $58, $00, $60, $80, $00, $04
	.BYTE	$81, $01, $28, $90, $4A, $00, $04, $91, $5A, $00, $60, $80
	.BYTE	$00, $04, $81, $01, $28, $90, $42, $00, $04, $91, $51, $00
	.BYTE	$60, $80, $00, $04, $81, $01, $28, $90, $55, $91, $45, $00
	.BYTE	$64, $80, $81, $01, $2C, $90, $56, $91, $4A, $01, $90, $91
	.BYTE	$3E, $01, $8A, $92, $48, $00, $06, $81, $00, $C8, $80, $00
	.BYTE	$C2, $90, $56, $82, $00, $06, $91, $47, $01, $8A, $90, $4F
	.BYTE	$92, $4A, $00, $C8, $90, $4E, $00, $6A, $81, $00, $5E, $80
	.BYTE	$00, $06, $90, $4F, $91, $47, $00, $C2, $82, $00, $06, $81
	.BYTE	$00, $C2, $91, $58, $00, $06, $90, $48, $01, $8A, $91, $4F
	.BYTE	$00, $06, $92, $4C, $00, $BB, $93, $4E, $00, $07, $81, $00
	.BYTE	$6A, $80, $00, $57, $83, $00, $07, $90, $48, $00, $03, $91
	.BYTE	$4F, $00, $C5, $80, $00, $06, $82, $00, $C2, $90, $56, $92
	.BYTE	$47, $00, $03, $81, $01, $86, $91, $54, $00, $06, $90, $45
	.BYTE	$82, $01, $8A, $81, $00, $06, $80, $00, $04, $90, $43, $00
	.BYTE	$03, $91, $53, $01, $83, $92, $51, $00, $0A, $80, $00, $03
	.BYTE	$90, $4A, $81, $00, $BB, $91, $4F, $82, $00, $C8, $91, $4E
	.BYTE	$00, $C8, $81, $00, $06, $91, $4F, $00, $C8, $91, $51, $01
	.BYTE	$2C, $81, $00, $07, $80, $00, $5D, $90, $4A, $00, $04, $91
	.BYTE	$3E, $00, $C4, $90, $4C, $00, $C5, $92, $4E, $00, $03, $80
	.BYTE	$00, $C5, $82, $00, $03, $90, $4F, $00, $C8, $90, $51, $00
	.BYTE	$C5, $92, $53, $00, $03, $80, $00, $04, $81, $00, $C1, $90
	.BYTE	$54, $82, $00, $03, $91, $40, $00, $62, $80, $00, $03, $81
	.BYTE	$01, $34, $90, $53, $91, $43, $00, $6C, $80, $81, $01, $49
	.BYTE	$90, $42, $00, $04, $91, $51, $00, $70, $80, $00, $03, $81
	.BYTE	$01, $6B, $90, $53, $91, $43, $00, $FB, $90, $56, $01, $05
	.BYTE	$80, $81, $00, $05, $90, $3B, $00, $04, $91, $4F, $01, $0D
	.BYTE	$80, $01, $18, $90, $3E, $00, $05, $92, $4E, $00, $05, $81
	.BYTE	$01, $20, $80, $01, $3E, $82, $00, $05, $90, $4F, $91, $4A
	.BYTE	$92, $47, $93, $43, $01, $4A, $83, $01, $5C, $93, $3E, $01
	.BYTE	$65, $83, $01, $7C, $93, $37, $0A, $23, $80, $81, $82, $00
	.BYTE	$15, $83
	.BYTE	$F0

	.END
